dist: xenial
language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install nuitka

script:
  - for f in examples/*_test.ntn; do python neutron "$f"; done
  - find neutron/libs -iname *.ntn -exec python3 neutron {} \;
  - python3 -m nuitka --follow-imports --include-plugin-directory=./neutron --show-progress --show-scons neutron
